version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: speechapi-db
    restart: always
    environment:
      POSTGRES_DB: speechdb          # Creates the "speechdb" database
      POSTGRES_USER: postgres        # Default PostgreSQL user
      POSTGRES_PASSWORD: postgres    # Default PostgreSQL password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  speechapi:
    build: .
    container_name: speechapi-app
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/speechdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"

volumes:
  pgdata: